routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/* Admin area */
Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'canDashboard']], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
    Route::group(['middleware' => ['permission:edit_users']], function () {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    });
    Route::group(['middleware' => ['permission:edit_menu']], function () {
        Route::resource('menus', 'MenuController', ['except' => 'show']);
        Route::resource('menuitems', 'MenuItemController', ['except' => 'show']);
    });
    Route::group(['middleware' => ['permission:edit_content']], function () {
        Route::resource('posts', 'PostController', ['except' => 'show']);
        Route::resource('categories', 'CategoryController', ['except' => 'show']);
        Route::resource('posts', 'PostController', ['except' => 'show']);
        Route::resource('pages', 'PageController', ['except' => 'show']);
        Route::resource('levels', 'LevelController', ['except' => 'show']);
        Route::resource('cycles', 'CycleController', ['except' => 'show']);
        Route::resource('classes', 'SchoolClassController', ['except' => 'show']);
        Route::resource('notes', 'NoteController', ['except' => 'show']);
        Route::resource('schools', 'SchoolController', ['except' => 'show']);
        Route::post('schools/filter', ['as' => 'schools.filter', 'uses' => 'SchoolController@filter']);
        Route::resource('schooltypes', 'SchoolTypeController', ['except' => 'show']);
        Route::resource('creates', 'CreateController', ['except' => 'show']);
        Route::resource('tools', 'ToolController', ['except' => 'show']);
        Route::resource('statuses', 'StatusController', ['except' => 'show']);
        Route::resource('ptypes', 'PTypeController', ['except' => 'show']);
        Route::resource('stypes', 'STypeController', ['except' => 'show']);
    });
    Route::group(['middleware' => ['permission:edit_branch']], function () {
        Route::resource('branches', 'BranchController', ['except' => 'show']);
        Route::resource('subjects', 'SubjectController', ['except' => 'show']);
        Route::resource('expected-outcomes', 'ExpectedOutcomeController', ['except' => 'show']);
        Route::resource('content-lines', 'ContentLineController', ['except' => 'show']);
        Route::resource('specific-outcomes', 'SpecificOutcomeController', ['except' => 'show']);
        Route::resource('skills', 'SkillController', ['except' => 'show']);
        Route::resource('branchnotes', 'BranchNoteController', ['except' => 'show']);
    });
    Route::get('approve', ['as' => 'approve', 'uses' => 'ApproveController@index']);
    Route::post('approve/filter', ['as' => 'approve.filter', 'uses' => 'ApproveController@filter']);
    Route::post('approve/package_approve', ['as' => 'approve.package_approve', 'uses' => 'ApproveController@package_approve']);
});

Route::get('/',    ['as'=>'home', 'uses'=>'GeneralController@index']);
Route::get('/404', ['as'=>'notfound', 'uses'=>'GeneralController@pagenotfound']);
Route::get('/401', ['as'=>'unauthorized', 'uses'=>'GeneralController@unauthorized']);

Route::get('/search', ['as'=>'search', 'uses'=>'SearchController@index']);

/* Глоссарий и новости и прочие посты */
Route::get('/glossary/{later?}', ['as'=>'glossary', 'uses'=>'GeneralController@glossary']);
Route::get('/news', ['as'=>'news', 'uses'=>'GeneralController@news']);
Route::get('/materials', ['as'=>'materials', 'uses'=>'GeneralController@materials']);
Route::get('/laws', ['as'=>'laws', 'uses'=>'GeneralController@laws']);
Route::get('/regulations', ['as'=>'regulations', 'uses'=>'GeneralController@regulations']);
Route::get('/guidelines', ['as'=>'guidelines', 'uses'=>'GeneralController@guidelines']);



/* Стандарт */
Route::get('/rivens',   ['as'=>'rivens', 'uses'=>'GeneralController@rivens']);
Route::get('/galuzes',  ['as'=>'galuzes', 'uses'=>'GeneralController@galuzes']);
Route::get('/zors',     ['as'=>'zors', 'uses'=>'GeneralController@zors']);
Route::get('/get_zors', ['as'=>'get_zors', 'uses'=>'GeneralController@get_zors']); /* ajax */
Route::get('/kors',     ['as'=>'kors', 'uses'=>'GeneralController@kors']);
Route::get('/get_kors', ['as'=>'get_kors', 'uses'=>'GeneralController@get_kors']); /* ajax */
Route::get('/get_post', ['as'=>'get_post', 'uses'=>'PostController@get_post']);   /* ajax */
Route::get('/note',     ['as'=>'note', 'uses'=>'GeneralController@note']);
Route::get('/get_note', ['as'=>'get_note', 'uses'=>'GeneralController@get_note']);   /* ajax */
Route::post('/get_posts',['as'=>'get_posts', 'uses'=>'SearchController@get_posts']);   /* ajax */


/* Школа */
Route::get('/school/users',    ['as'=>'school-users', 'uses'=>'SchoolController@schoolusers', 'middleware'=>'auth']);
Route::get('/school/users-status',    ['as'=>'school-users-status', 'uses'=>'SchoolController@schoolusersstatus', 'middleware'=>'auth']);
Route::get('/school/kors',    ['as'=>'school-kors', 'uses'=>'SchoolController@kors', 'middleware'=>'auth']);
Route::post('/school/kors-delete',    ['as'=>'school-kors-delete', 'uses'=>'SchoolController@korsdelete', 'middleware'=>'auth']);
Route::post('/school/kors-save',    ['as'=>'school-kors-save', 'uses'=>'SchoolController@korssave', 'middleware'=>'auth']);

Route::get('/school/package', ['as'=>'school-package-list', 'uses'=>'SchoolController@package_list', 'middleware'=>'auth']);
Route::post('/school/package-save',    ['as'=>'school-package-save', 'uses'=>'SchoolController@package_save', 'middleware'=>'auth']);
Route::post('/school/package-get',     ['as'=>'school-package-get',  'uses'=>'SchoolController@package_get',  'middleware'=>'auth']);
Route::post('/school/package-delete',  ['as'=>'school-package-delete', 'uses'=>'SchoolController@package_delete', 'middleware'=>'auth']);
Route::post('/school/package-approve', ['as'=>'school-package-approve', 'uses'=>'SchoolController@package_approve', 'middleware'=>'auth']);


/* Конструктор */
Route::get( '/plans/list/{id_list?}', ['as'=>'user-plans-list', 'uses'=>'PlanController@plans_list','middleware'=>'plansmiddle']);
Route::get( '/plans/view/{id_plan?}', ['as'=>'user-plan-view', 'uses'=>'PlanController@plan_view','middleware'=>'planmiddle']);
Route::get( '/plans/edit/{id_plan?}', ['as'=>'user-plans-edit', 'uses'=>'PlanController@plans_edit','middleware'=>'planeditmiddle']);
Route::post('/plans/save',            ['as'=>'user-plans-save', 'uses'=>'PlanController@plans_save']);
Route::get( '/plans/delete',          ['as'=>'user-plans-delete', 'uses'=>'PlanController@plans_delete']);
Route::get( '/plans/check',           ['as'=>'user-plans-check', 'uses'=>'PlanController@plans_check']);
Route::get ('/plans/get-all',         ['as'=>'user-plans-get-all', 'uses'=>'PlanController@plans_get_all']);  /* ajax */


Route::get( '/plans/new-from-basic',  ['as'=>'user-plans-new-from-basic', 'uses'=>'PlanController@new_plan_from_basic']); /* ajax */
Route::get( '/plans/new-from-typical',['as'=>'user-plans-new-from-typical', 'uses'=>'PlanController@new_plan_from_typical']); /* ajax */

Route::post( '/plans/perevirka',       ['as'=>'user-plans-perevirka', 'uses'=>'PlanController@plans_perevirka']);

Route::post('/plans/popup',           ['as'=>'user-plans-popup', 'uses'=>'PlanController@plan_popup']);




Route::get( '/programs/list/{id_list?}',    ['as'=>'user-programs-list', 'uses'=>'ProgramController@programs_list','middleware'=>'plansmiddle']);
Route::get( '/programs/edit/{id_program?}', ['as'=>'user-program-edit', 'uses'=>'ProgramController@program_edit','middleware'=>'programeditmiddle']);
Route::get( '/programs/view/{id_program?}', ['as'=>'user-program-view', 'uses'=>'ProgramController@program_view','middleware'=>'programmiddle']);
Route::post('/programs/save',               ['as'=>'user-program-save', 'uses'=>'ProgramController@program_save','middleware'=>'programmiddle']);
Route::get( '/programs/free',               ['as'=>'user-program-free', 'uses'=>'ProgramController@program_free','middleware'=>'programmiddle']);
Route::get( '/programs/change',             ['as'=>'user-program-change-editor', 'uses'=>'ProgramController@program_change_editor','middleware'=>'programmiddle']);
Route::get( '/programs/is_open',            ['as'=>'user-program-is-open', 'uses'=>'ProgramController@program_is_open','middleware'=>'programmiddle']);
Route::post('/programs/save-users', ['as'=>'user-program-save-users', 'uses'=>'ProgramController@program_save_users','middleware'=>'programmiddle']);
Route::post('/programs/create-new',         ['as'=>'user-program-create-new', 'uses'=>'ProgramController@program_create_new']);
Route::post('/programs/delete',             ['as'=>'user-program-delete', 'uses'=>'ProgramController@program_delete']);
Route::get ('/programs/get-all',            ['as'=>'user-program-get-all', 'uses'=>'ProgramController@program_get_all']);  /* ajax */
Route::post('/programs/new-from-typical',   ['as'=>'user-programs-new-from-typical', 'uses'=>'ProgramController@new_program_from_typical', 'middleware'=>'auth']); /* ajax */
Route::post('/programs/popup',              ['as'=>'user-programs-popup', 'uses'=>'ProgramController@program_popup']);

/* User */

Route::get( '/user/profile',            ['as'=>'user-profile', 'uses'=>'UserController@profile', 'middleware'=>'auth']);

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

use App\User;
use Auth;
use App\Http\Controllers\Controller;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

//Enables us to output flash messaging
use Session;

class AdminController extends Controller 
{ 
    public function index()
    {
        return view('dashboard.index', [
                        'user' => Auth::user(),
                    ]);
    }

}

app/Http/Controllers/Dashboard/ApproveController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\School;
use App\SchoolType;
use App\Package;
use App\Plan;
use App\Program;

class ApproveController extends Controller
{

    public $data = [];

    public function __construct()
    {
        # code...
    }

    public function index()
    {

        $this->data['current_school_regions'] = '';

        $this->data['school_regions'] = School::select('region_school')->distinct()->orderBy('region_school', 'asc')->get();

        $this->data['packages'] = (object)[];

        return view('dashboard.approve.index', $this->data);
    }


    public function filter(Request $request)
    {

        $school_region = $request['school_region'] ? $request['school_region'] : '';

        $this->data['current_school_regions'] = $school_region;
        $this->data['school_regions'] = School::select('region_school')->distinct()->orderBy('region_school', 'asc')->get();

        $this->data['packages'] = Package::where('packages.id_status', 6)->leftjoin('schools','packages.id_school','=','schools.id_school')->where('region_school', $school_region)->leftjoin('statuses','packages.id_status','=','statuses.id_status')->get();

        return view('dashboard.approve.index', $this->data);
    }


    public function package_approve(Request $request)
    {
        $result = [];
        $id_package = $request->input('id_package') ? (int)$request->input('id_package') : 0;
        $id_status = $request->input('id_status') ? (int)$request->input('id_status') : 8;
        $critical_package = $request->input('critical_package') ? $request->input('critical_package') : '';
        $package = Package::findOrFail($id_package);
        if ($package){

            $plan_in_package = json_decode($package->plans_package);
            /* Устанавливае статусы всем планам и программам */
            foreach ($plan_in_package as $plan) {
                //$current_plan = Plan::where('id_plan', $plan->id_plan)->first();
                $current_plan = Plan::findOrFail($plan->id_plan);
                if ($current_plan){
                    $programs_in_plan = json_decode($current_plan->content_plan);
                    foreach ($programs_in_plan as $program) {
                        //$current_program = Program::where('id_program', $program->program)->first();
                        $current_program = Program::findOrFail($program->program);
                        if ($current_program){
                            $current_program->id_status = $id_status;
                            $current_program->save();
                        }
                    }
                    $current_plan->id_status = $id_status;
                    $current_plan->save();
                }
            }

            $package->id_status = $id_status;
            $package->approve_user = auth()->user()->id;
            $package->critical_package = $critical_package;
            $package->save();

        }

        $result['package'] = $package;
        return json_encode($result);
    }

}

app/Http/Controllers/Dashboard/BranchController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Spatie\Permission\Models\Permission;
use App\Galuz as Branch;
use Illuminate\Http\Request;
use App\Http\Controllers\Dashboard\AdminController;

class BranchController extends AdminController
{
    public function index()
    {
        $branches = Branch::all();

        return view('dashboard.branches.index', compact('branches'));
    }

    public function create()
    {
        if (!Auth::user()->can('edit_branches')) {
            abort('401');
        }
        return view('dashboard.branches.create');
    }

    public function store(Request $request)
    {
        if (!Auth::user()->can('edit_content')){
            abort('401');
        }

        $this->validate($request, [
            'branch_name' => 'required|unique:galuzes,name_galuz',
            'branch_label' => 'required|unique:galuzes,marking_galuz',
            'branch_color' => 'required|unique:galuzes,color_galuz',
        ]);

        $permission = new Permission;
        $permission->name = $request['branch_label'];
        $permission->save();

        $branch = new Branch;
        $branch->name_galuz = $request['branch_name'];
        $branch->marking_galuz = $request['branch_label'];
        $branch->text_galuz = $request['branch_text'];
        if ($branch->text_galuz == null) {
            $branch->text_galuz = '';
        }
        $branch->color_galuz = $request['branch_color'];
        
        $branch->save();

        return redirect()->route('branches.index')
        ->with('flash_message',
             'Галузь '.$branch->name_galuz.' створена!');
    }

    public function edit($branch_id)
    {
        $branch = Branch::find($branch_id);

        if (!Auth::user()->hasAnyPermission('edit_content', $branch->marking_galuz)){
            abort('401');
        }

        return view('dashboard.branches.edit', compact('branch'));
    }

    public function update(Request $request, $branch_id)
    {
        $branch = Branch::find($branch_id);

        if (!Auth::user()->hasAnyPermission('edit_content', $branch->marking_galuz)){
            abort('401');
        }

        $this->validate($request, [
            'name_galuz' => 'required|unique:galuzes,name_galuz,'.$branch->id_galuz.',id_galuz',
            'marking_galuz' => 'required|unique:galuzes,marking_galuz,'.$branch->id_galuz.',id_galuz',
            'color_galuz' => 'required|unique:galuzes,color_galuz,'.$branch->id_galuz.',id_galuz',
        ]);

        $permission = Permission::where('name', $branch->marking_galuz)->first();
        $permission->name = $request['marking_galuz'];
        $permission->save();

        $branch->name_galuz = $request['name_galuz'];
        if (Auth::user()->can('edit_content')) {
            $branch->marking_galuz = $request['marking_galuz'];
        }
        $branch->text_galuz = $request['text_galuz'];

        if ($branch->text_galuz == null) {
            $branch->text_galuz = '';
        }

        $branch->color_galuz = $request['color_galuz'];
        $branch->save();

        return redirect()->route('branches.index')
        ->with('flash_message',
             'Галузь '.$branch->name_galuz.' оновлена!');
    }

    public function destroy($branch_id)
    {
        if (!Auth::user()->hasAnyPermission('edit_content', 'admin')) {
            abort('401');
        }

        $branch = Branch::find($branch_id);
        $branch->delete();

        $permission = Permission::where('name', $branch->marking_galuz)->first();
        $permission->delete();

        return redirect()->route('branches.index')
            ->with('flash_message',
             'Галузь '.$branch->name_galuz.' видалена!');
    }
}

resources/views/dashboard/specific-outcomes/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Додати КОР</title>
@endsection

@section('content')

<div class='col-lg-4 col-lg-offset-4'>
    
    <h1>Додати КОР</h1>

    {{ Form::open(['route' => 'specific-outcomes.index']) }}

        <div class="form-group">
            {{ Form::label('specific_outcome_name', 'Назва') }}
            {{ Form::text('specific_outcome_name', null, ['class' => 'form-control' . ($errors->has('specific_outcome_name') ? ' is-invalid' : '')]) }}

            @if($errors->has('specific_outcome_name'))
                @foreach ($errors->get('specific_outcome_name') as $message)
                    <div class="invalid-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('specific_outcome_key', 'Код КОРа') }}
            {{ Form::text('specific_outcome_key', null, ['class' => 'form-control' . ($errors->has('specific_outcome_key') ? ' is-invalid' : '')]) }}

            @if($errors->has('specific_outcome_key'))
                @foreach ($errors->get('specific_outcome_key') as $message)
                    <div class="invalid-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('expected_outcome_id', 'ЗОР', ['class' => 'form-control-label']) }}
            {{ Form::select('expected_outcome_id', $expected_outcomes, 0, ['class' => 'form-control' . ($errors->has('expected_outcome_id') ? 'is-invalid' : '')]) }}

            @if($errors->has('expected_outcome_id'))
                @foreach ($errors->get('expected_outcome_id') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('content_line_id', 'Змістова лінія', ['class' => 'form-control-label']) }}
            {{ Form::select('content_line_id', $content_lines, 0, ['class' => 'form-control' . ($errors->has('content_line_id') ? 'is-invalid' : '')]) }}

            @if($errors->has('content_line_id'))
                @foreach ($errors->get('content_line_id') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        {{ Form::submit('Додати', ['class' => 'btn btn-primary']) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/dashboard/specific-outcomes/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Редагувати ЗОР</title>
@endsection

@section('content')

<h1>Редагувати "{{$specific_outcome->name_kor}}"</h1>

<div class='col-lg-4 col-lg-offset-4'>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    {{ Form::model($specific_outcome, ['route' => ['specific-outcomes.update', $specific_outcome->id_kor], 'method' => 'PUT']) }}

        <div class="form-group">
            {{ Form::label('name_kor', 'Назва категорії') }}
            {{ Form::text('name_kor', null, ['class' => 'form-control' . ($errors->has('name_kor') ? ' form-control-danger' : '')]) }}

            @if($errors->has('name_kor'))
                @foreach ($errors->get('name_kor') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('key_kor', 'Код') }}
            {{ Form::text('key_kor', null, ['class' => 'form-control' . ($errors->has('key_kor') ? ' form-control-danger' : '')]) }}

            @if($errors->has('key_kor'))
                @foreach ($errors->get('key_kor') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('id_zor', 'ЗОР', ['class' => 'form-control-label']) }}
            {{ Form::select('id_zor', $expected_outcomes, null, ['class' => 'form-control' . ($errors->has('id_zor') ? 'is-invalid' : '')]) }}

            @if($errors->has('id_zor'))
                @foreach ($errors->get('id_zor') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        <div class="form-group">
            {{ Form::label('id_zmist', 'Змістова лінія', ['class' => 'form-control-label']) }}
            {{ Form::select('id_zmist', $content_lines, null, ['class' => 'form-control' . ($errors->has('id_zmist') ? 'is-invalid' : '')]) }}

            @if($errors->has('id_zmist'))
                @foreach ($errors->get('id_zmist') as $message)
                    <div class="form-control-feedback">{{ $message }}</div>
                @endforeach
            @endif
        </div>

        {{ Form::submit('Редагувати', ['class' => 'btn btn-success']) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/dashboard/specific-outcomes/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>КОРи</title>
@endsection

@section('content')

    <h1>КОРи</h1>
    <div class="col-lg-3">
        <div class="form-group">
            <a href="{{ route('specific-outcomes.create') }}" class="btn btn-success">Додати КОР</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>КОР</th>
                <th>Зор</th>
                <th>Змістова лінія</th>
                <th>Код</th>
                <th>Операції</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($specific_outcomes as $specific_outcome)
                {{-- {{ dump($specific_outcome->getBranchByContentLine()) }} --}}
                @if(Auth::user()->hasAnyPermission($specific_outcome->getBranchByContentLine() ? $specific_outcome->getBranchByContentLine() : 'dashboard', 'edit_content'))
                    <tr>
                        <td>{{ $specific_outcome->name_kor }}</td>
                        <td>{{ $specific_outcome->getSpecificOutcomeExpectedOutcome() }}</td>
                        <td>{{ $specific_outcome->getSpecificOutcomeContentLine() }}</td>
                        <td>{{ $specific_outcome->key_kor }}</td>
                        <td>
                            <a href="{{ route('specific-outcomes.edit', $specific_outcome->id_kor) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Редагувати</a>
                            {!! Form::open(['style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => ['specific-outcomes.destroy', $specific_outcome->id_kor] ]) !!}
                                {!! Form::submit('Видалити', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endif
            @endforeach
        </tbody>
    </table>

    {{ $specific_outcomes->links() }}

@endsection